server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FredrickRichardG/cloud-config-server/tree/main/src/main/resources/

  application:
    name: config-server


