server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FredrickRichardG/cloud-config-server-setup
          repos:
            staging-properties-repo:
              pattern: config-client/staging
              uri: https://github.com/FredrickRichardG/cloud-config-server-setup
              search-paths: config-repo/{application}/{profile}

            prod-properties-repo:
              pattern: config-client/prod
              uri: https://github.com/FredrickRichardG/cloud-config-server-setup
              search-paths: config-repo/{profile}
            any-properties-repo:
              pattern: config-client*/*
              uri: https://github.com/FredrickRichardG/cloud-config-server-setup
              search-paths: config-repo



  application:
    name: config-server


